const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { z } = require('zod');
const { receiveStock, createOrder, transitionOrder } = require('./services/inventory');
const JWT_SECRET = process.env.JWT_SECRET || 'development-only-change-me';

function createApp(db) {
  const app = express(); app.use(helmet({ contentSecurityPolicy: false })); app.use(cors()); app.use(express.json()); app.use(morgan('tiny'));
  const sign = u => jwt.sign({ sub: u.id, role: u.role, name: u.name }, JWT_SECRET, { expiresIn: '8h' });
  const auth = (req,res,next) => { try { req.user = jwt.verify((req.headers.authorization || '').replace('Bearer ', ''), JWT_SECRET); next(); } catch { res.status(401).json({ error: 'Authentication required' }); } };
  const roles = (...allowed) => (req,res,next) => allowed.includes(req.user.role) ? next() : res.status(403).json({ error: 'Insufficient permission' });
  const fail = (res,error) => res.status(400).json({ error: error.message || 'Invalid request' });
  const availability = `COALESCE((SELECT SUM(available_quantity) FROM inventory_batches b WHERE b.product_id = p.id AND b.expiry_date > date('now')), 0)`;
  app.get('/api/health', (_req,res)=>res.json({ status:'ok' }));
  app.post('/api/auth/login', (req,res) => { try { const {email,password}=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body); const user=db.prepare('SELECT * FROM users WHERE email=?').get(email); if(!user || !bcrypt.compareSync(password,user.password_hash)) return res.status(401).json({error:'Invalid email or password'}); res.json({token:sign(user),user:{id:user.id,name:user.name,email:user.email,role:user.role}}); } catch(e){fail(res,e);} });
  app.get('/api/catalogue', auth, (req,res) => { const q=(req.query.q||'').trim(); const rows=db.prepare(`SELECT p.*, c.name category, ${availability} available_quantity FROM products p JOIN categories c ON c.id=p.category_id WHERE p.archived_at IS NULL AND p.marketplace_visible=1 AND p.availability_status='AVAILABLE' AND ${availability}>0 ${q ? "AND (p.name LIKE @query OR p.brand LIKE @query OR p.composition LIKE @query OR p.manufacturer LIKE @query)" : ''} ORDER BY p.name`).all(q?{query:`%${q}%`}:{}); res.json({items:rows.map(p=>({...p,marketplaceVisible:!!p.marketplace_visible,availableQuantity:p.available_quantity}))}); });
  app.get('/api/products', auth, roles('WHOLESALER'), (_req,res)=>res.json({items:db.prepare(`SELECT p.*,c.name category,${availability} available_quantity FROM products p JOIN categories c ON c.id=p.category_id WHERE p.archived_at IS NULL ORDER BY p.created_at DESC`).all()}));
  app.post('/api/products', auth, roles('WHOLESALER'), (req,res)=>{try{const data=z.object({name:z.string().min(2),brand:z.string().min(2),composition:z.string().min(2),categoryId:z.string(),mrp:z.number().nonnegative(),wholesalePrice:z.number().nonnegative(),gstRate:z.number().min(0).default(0),minimumStock:z.number().int().nonnegative().default(0),marketplaceVisible:z.boolean().default(true),manufacturer:z.string().optional(),packSize:z.string().optional(),classification:z.string().optional(),description:z.string().optional(),imageUrl:z.string().url().optional()}).parse(req.body); const id=require('node:crypto').randomUUID(); db.prepare('INSERT INTO products(id,name,brand,composition,category_id,mrp,wholesale_price,gst_rate,minimum_stock,marketplace_visible,manufacturer,pack_size,classification,description,image_url) VALUES (@id,@name,@brand,@composition,@categoryId,@mrp,@wholesalePrice,@gstRate,@minimumStock,@marketplaceVisible,@manufacturer,@packSize,@classification,@description,@imageUrl)').run({...data,id,marketplaceVisible:data.marketplaceVisible?1:0});res.status(201).json({id});}catch(e){fail(res,e)}});
  app.post('/api/inventory/receive',auth,roles('WHOLESALER'),(req,res)=>{try{const data=z.object({productId:z.string(),batchNumber:z.string().min(1),expiryDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),quantity:z.number().int().positive(),purchasePrice:z.number().nonnegative(),sellingPrice:z.number().nonnegative().optional(),warehouse:z.string().optional(),notes:z.string().optional()}).parse(req.body);res.status(201).json({batchId:receiveStock(db,{...data,actorId:req.user.sub})});}catch(e){fail(res,e)}});
  app.get('/api/inventory/batches',auth,roles('WHOLESALER'),(_req,res)=>res.json({items:db.prepare(`SELECT b.*,p.name product_name,julianday(b.expiry_date)-julianday('now') days_remaining FROM inventory_batches b JOIN products p ON p.id=b.product_id ORDER BY b.expiry_date`).all()}));
  app.post('/api/orders',auth,roles('CUSTOMER'),(req,res)=>{try{const data=z.object({items:z.array(z.object({productId:z.string(),quantity:z.number().int().positive()})).min(1),shippingAddress:z.string().optional()}).parse(req.body);res.status(201).json({order:createOrder(db,{...data,customerId:req.user.sub,actorId:req.user.sub})});}catch(e){fail(res,e)}});
  app.get('/api/orders',auth,(req,res)=>{const own=req.user.role==='CUSTOMER';const rows=db.prepare(`SELECT o.*,(SELECT COUNT(*) FROM order_items i WHERE i.order_id=o.id) item_count FROM orders o ${own?'WHERE o.customer_id=?':''} ORDER BY o.created_at DESC`).all(...(own?[req.user.sub]:[]));res.json({items:rows});});
  app.patch('/api/orders/:id/status',auth,roles('WHOLESALER'),(req,res)=>{try{const {status}=z.object({status:z.enum(['CONFIRMED','REJECTED','PROCESSING','PACKED','DISPATCHED','DELIVERED','CANCELLED','RETURNED'])}).parse(req.body);res.json({order:transitionOrder(db,{orderId:req.params.id,status,actorId:req.user.sub})});}catch(e){fail(res,e)}});
  app.get('/api/dashboard',auth,roles('WHOLESALER'),(_req,res)=>{const scalar=sql=>db.prepare(sql).get().value;res.json({totalProducts:scalar("SELECT COUNT(*) value FROM products WHERE archived_at IS NULL"),inStock:scalar(`SELECT COUNT(*) value FROM products p WHERE ${availability}>0`),outOfStock:scalar(`SELECT COUNT(*) value FROM products p WHERE ${availability}=0`),lowStock:scalar(`SELECT COUNT(*) value FROM products p WHERE ${availability}<=p.minimum_stock`),expiringSoon:scalar("SELECT COUNT(*) value FROM inventory_batches WHERE expiry_date BETWEEN date('now') AND date('now','+90 days') AND quantity>0"),pendingOrders:scalar("SELECT COUNT(*) value FROM orders WHERE status='PENDING'"),pendingRequirements:scalar("SELECT COUNT(*) value FROM requirements WHERE status IN ('NEW','REVIEWING')"),stockValue:scalar('SELECT COALESCE(SUM(quantity*purchase_price),0) value FROM inventory_batches')});});
  app.get('/api/requirements',auth,(req,res)=>{const own=req.user.role==='CUSTOMER';res.json({items:db.prepare(`SELECT r.*,u.name customer_name FROM requirements r JOIN users u ON u.id=r.customer_id ${own?'WHERE r.customer_id=?':''} ORDER BY r.created_at DESC`).all(...(own?[req.user.sub]:[]))});});
  app.post('/api/requirements',auth,roles('CUSTOMER'),(req,res)=>{try{const data=z.object({medicineName:z.string().min(2),composition:z.string().optional(),quantity:z.number().int().positive(),notes:z.string().optional(),priority:z.enum(['LOW','NORMAL','HIGH']).default('NORMAL')}).parse(req.body);const id=require('node:crypto').randomUUID();db.prepare('INSERT INTO requirements(id,customer_id,medicine_name,composition,quantity,notes,priority) VALUES(?,?,?,?,?,?,?)').run(id,req.user.sub,data.medicineName,data.composition||null,data.quantity,data.notes||null,data.priority);res.status(201).json({id});}catch(e){fail(res,e)}});
  app.use(express.static(require('node:path').join(__dirname,'..','public'))); app.use((err,_req,res,_next)=>res.status(500).json({error:err.message||'Internal server error'})); return app;
}
module.exports={createApp};
